// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: pfi.proto

package invoke

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiSwapPFI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      []byte      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator []byte      `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Owner   []byte      `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Token   string      `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	From    string      `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To      string      `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	Hash    []byte      `protobuf:"bytes,7,opt,name=hash,proto3" json:"hash,omitempty"`
	Timeout int64       `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Assets  []*AssetPFI `protobuf:"bytes,9,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (x *MultiSwapPFI) Reset() {
	*x = MultiSwapPFI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pfi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiSwapPFI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSwapPFI) ProtoMessage() {}

func (x *MultiSwapPFI) ProtoReflect() protoreflect.Message {
	mi := &file_pfi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSwapPFI.ProtoReflect.Descriptor instead.
func (*MultiSwapPFI) Descriptor() ([]byte, []int) {
	return file_pfi_proto_rawDescGZIP(), []int{0}
}

func (x *MultiSwapPFI) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MultiSwapPFI) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *MultiSwapPFI) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *MultiSwapPFI) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MultiSwapPFI) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MultiSwapPFI) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MultiSwapPFI) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *MultiSwapPFI) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *MultiSwapPFI) GetAssets() []*AssetPFI {
	if x != nil {
		return x.Assets
	}
	return nil
}

type AssetPFI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group  string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Amount []byte `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *AssetPFI) Reset() {
	*x = AssetPFI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pfi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetPFI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPFI) ProtoMessage() {}

func (x *AssetPFI) ProtoReflect() protoreflect.Message {
	mi := &file_pfi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPFI.ProtoReflect.Descriptor instead.
func (*AssetPFI) Descriptor() ([]byte, []int) {
	return file_pfi_proto_rawDescGZIP(), []int{1}
}

func (x *AssetPFI) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *AssetPFI) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

type SwapPFI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator []byte `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Owner   []byte `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Token   string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Amount  []byte `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	From    string `protobuf:"bytes,6,opt,name=from,proto3" json:"from,omitempty"`
	To      string `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`
	Hash    []byte `protobuf:"bytes,8,opt,name=hash,proto3" json:"hash,omitempty"`
	Timeout int64  `protobuf:"varint,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *SwapPFI) Reset() {
	*x = SwapPFI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pfi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwapPFI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapPFI) ProtoMessage() {}

func (x *SwapPFI) ProtoReflect() protoreflect.Message {
	mi := &file_pfi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapPFI.ProtoReflect.Descriptor instead.
func (*SwapPFI) Descriptor() ([]byte, []int) {
	return file_pfi_proto_rawDescGZIP(), []int{2}
}

func (x *SwapPFI) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SwapPFI) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *SwapPFI) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *SwapPFI) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SwapPFI) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *SwapPFI) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SwapPFI) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SwapPFI) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *SwapPFI) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type WriteElementPFI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsDeleted bool   `protobuf:"varint,3,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
}

func (x *WriteElementPFI) Reset() {
	*x = WriteElementPFI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pfi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteElementPFI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteElementPFI) ProtoMessage() {}

func (x *WriteElementPFI) ProtoReflect() protoreflect.Message {
	mi := &file_pfi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteElementPFI.ProtoReflect.Descriptor instead.
func (*WriteElementPFI) Descriptor() ([]byte, []int) {
	return file_pfi_proto_rawDescGZIP(), []int{3}
}

func (x *WriteElementPFI) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteElementPFI) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WriteElementPFI) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ResponseErrorPFI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ResponseErrorPFI) Reset() {
	*x = ResponseErrorPFI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pfi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseErrorPFI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseErrorPFI) ProtoMessage() {}

func (x *ResponseErrorPFI) ProtoReflect() protoreflect.Message {
	mi := &file_pfi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseErrorPFI.ProtoReflect.Descriptor instead.
func (*ResponseErrorPFI) Descriptor() ([]byte, []int) {
	return file_pfi_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseErrorPFI) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseErrorPFI) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SwapResponsePFI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     []byte             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error  *ResponseErrorPFI  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Writes []*WriteElementPFI `protobuf:"bytes,3,rep,name=writes,proto3" json:"writes,omitempty"`
}

func (x *SwapResponsePFI) Reset() {
	*x = SwapResponsePFI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pfi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwapResponsePFI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapResponsePFI) ProtoMessage() {}

func (x *SwapResponsePFI) ProtoReflect() protoreflect.Message {
	mi := &file_pfi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapResponsePFI.ProtoReflect.Descriptor instead.
func (*SwapResponsePFI) Descriptor() ([]byte, []int) {
	return file_pfi_proto_rawDescGZIP(), []int{5}
}

func (x *SwapResponsePFI) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SwapResponsePFI) GetError() *ResponseErrorPFI {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SwapResponsePFI) GetWrites() []*WriteElementPFI {
	if x != nil {
		return x.Writes
	}
	return nil
}

type TxResponsePFI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     []byte             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method string             `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Error  *ResponseErrorPFI  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Writes []*WriteElementPFI `protobuf:"bytes,4,rep,name=writes,proto3" json:"writes,omitempty"`
}

func (x *TxResponsePFI) Reset() {
	*x = TxResponsePFI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pfi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxResponsePFI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxResponsePFI) ProtoMessage() {}

func (x *TxResponsePFI) ProtoReflect() protoreflect.Message {
	mi := &file_pfi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxResponsePFI.ProtoReflect.Descriptor instead.
func (*TxResponsePFI) Descriptor() ([]byte, []int) {
	return file_pfi_proto_rawDescGZIP(), []int{6}
}

func (x *TxResponsePFI) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TxResponsePFI) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TxResponsePFI) GetError() *ResponseErrorPFI {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *TxResponsePFI) GetWrites() []*WriteElementPFI {
	if x != nil {
		return x.Writes
	}
	return nil
}

type BatchResponsePFI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxResponses      []*TxResponsePFI   `protobuf:"bytes,1,rep,name=tx_responses,json=txResponses,proto3" json:"tx_responses,omitempty"`
	CreatedSwaps     []*SwapPFI         `protobuf:"bytes,2,rep,name=created_swaps,json=createdSwaps,proto3" json:"created_swaps,omitempty"`
	SwapResponses    []*SwapResponsePFI `protobuf:"bytes,3,rep,name=swap_responses,json=swapResponses,proto3" json:"swap_responses,omitempty"`
	SwapKeyResponses []*SwapResponsePFI `protobuf:"bytes,4,rep,name=swap_key_responses,json=swapKeyResponses,proto3" json:"swap_key_responses,omitempty"`
	CreatedMultiSwap []*MultiSwapPFI    `protobuf:"bytes,5,rep,name=created_multi_swap,json=createdMultiSwap,proto3" json:"created_multi_swap,omitempty"`
}

func (x *BatchResponsePFI) Reset() {
	*x = BatchResponsePFI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pfi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchResponsePFI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponsePFI) ProtoMessage() {}

func (x *BatchResponsePFI) ProtoReflect() protoreflect.Message {
	mi := &file_pfi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponsePFI.ProtoReflect.Descriptor instead.
func (*BatchResponsePFI) Descriptor() ([]byte, []int) {
	return file_pfi_proto_rawDescGZIP(), []int{7}
}

func (x *BatchResponsePFI) GetTxResponses() []*TxResponsePFI {
	if x != nil {
		return x.TxResponses
	}
	return nil
}

func (x *BatchResponsePFI) GetCreatedSwaps() []*SwapPFI {
	if x != nil {
		return x.CreatedSwaps
	}
	return nil
}

func (x *BatchResponsePFI) GetSwapResponses() []*SwapResponsePFI {
	if x != nil {
		return x.SwapResponses
	}
	return nil
}

func (x *BatchResponsePFI) GetSwapKeyResponses() []*SwapResponsePFI {
	if x != nil {
		return x.SwapKeyResponses
	}
	return nil
}

func (x *BatchResponsePFI) GetCreatedMultiSwap() []*MultiSwapPFI {
	if x != nil {
		return x.CreatedMultiSwap
	}
	return nil
}

var File_pfi_proto protoreflect.FileDescriptor

var file_pfi_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x66, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x69, 0x6e, 0x76,
	0x6f, 0x6b, 0x65, 0x22, 0xe0, 0x01, 0x0a, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x77, 0x61,
	0x70, 0x50, 0x46, 0x49, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x06,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69,
	0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x46, 0x49, 0x52, 0x06,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x22, 0x38, 0x0a, 0x08, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50,
	0x46, 0x49, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0xc9, 0x01, 0x0a, 0x07, 0x53, 0x77, 0x61, 0x70, 0x50, 0x46, 0x49, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x58, 0x0a, 0x0f,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x46, 0x49, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x3c, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x50, 0x46, 0x49, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x82, 0x01, 0x0a, 0x0f, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x46, 0x49, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x50, 0x46,
	0x49, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x06, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e, 0x76, 0x6f, 0x6b,
	0x65, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x46,
	0x49, 0x52, 0x06, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x0d, 0x54, 0x78,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x46, 0x49, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x2e, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x50, 0x46, 0x49, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x06, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x2e, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x46, 0x49, 0x52, 0x06, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x73, 0x22, 0xcd, 0x02, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x46, 0x49, 0x12, 0x38, 0x0a, 0x0c, 0x74, 0x78, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x2e, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x46, 0x49, 0x52, 0x0b, 0x74, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x73,
	0x77, 0x61, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x69, 0x6e, 0x76,
	0x6f, 0x6b, 0x65, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x50, 0x46, 0x49, 0x52, 0x0c, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x53, 0x77, 0x61, 0x70, 0x73, 0x12, 0x3e, 0x0a, 0x0e, 0x73, 0x77, 0x61,
	0x70, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x46, 0x49, 0x52, 0x0d, 0x73, 0x77, 0x61, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x12, 0x73, 0x77, 0x61,
	0x70, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x2e, 0x53,
	0x77, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x46, 0x49, 0x52, 0x10,
	0x73, 0x77, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73,
	0x12, 0x42, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x75, 0x6c, 0x74,
	0x69, 0x5f, 0x73, 0x77, 0x61, 0x70, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69,
	0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x77, 0x61, 0x70, 0x50,
	0x46, 0x49, 0x52, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x53, 0x77, 0x61, 0x70, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pfi_proto_rawDescOnce sync.Once
	file_pfi_proto_rawDescData = file_pfi_proto_rawDesc
)

func file_pfi_proto_rawDescGZIP() []byte {
	file_pfi_proto_rawDescOnce.Do(func() {
		file_pfi_proto_rawDescData = protoimpl.X.CompressGZIP(file_pfi_proto_rawDescData)
	})
	return file_pfi_proto_rawDescData
}

var file_pfi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pfi_proto_goTypes = []any{
	(*MultiSwapPFI)(nil),     // 0: invoke.MultiSwapPFI
	(*AssetPFI)(nil),         // 1: invoke.AssetPFI
	(*SwapPFI)(nil),          // 2: invoke.SwapPFI
	(*WriteElementPFI)(nil),  // 3: invoke.WriteElementPFI
	(*ResponseErrorPFI)(nil), // 4: invoke.ResponseErrorPFI
	(*SwapResponsePFI)(nil),  // 5: invoke.SwapResponsePFI
	(*TxResponsePFI)(nil),    // 6: invoke.TxResponsePFI
	(*BatchResponsePFI)(nil), // 7: invoke.BatchResponsePFI
}
var file_pfi_proto_depIdxs = []int32{
	1,  // 0: invoke.MultiSwapPFI.assets:type_name -> invoke.AssetPFI
	4,  // 1: invoke.SwapResponsePFI.error:type_name -> invoke.ResponseErrorPFI
	3,  // 2: invoke.SwapResponsePFI.writes:type_name -> invoke.WriteElementPFI
	4,  // 3: invoke.TxResponsePFI.error:type_name -> invoke.ResponseErrorPFI
	3,  // 4: invoke.TxResponsePFI.writes:type_name -> invoke.WriteElementPFI
	6,  // 5: invoke.BatchResponsePFI.tx_responses:type_name -> invoke.TxResponsePFI
	2,  // 6: invoke.BatchResponsePFI.created_swaps:type_name -> invoke.SwapPFI
	5,  // 7: invoke.BatchResponsePFI.swap_responses:type_name -> invoke.SwapResponsePFI
	5,  // 8: invoke.BatchResponsePFI.swap_key_responses:type_name -> invoke.SwapResponsePFI
	0,  // 9: invoke.BatchResponsePFI.created_multi_swap:type_name -> invoke.MultiSwapPFI
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pfi_proto_init() }
func file_pfi_proto_init() {
	if File_pfi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pfi_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MultiSwapPFI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pfi_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AssetPFI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pfi_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SwapPFI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pfi_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*WriteElementPFI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pfi_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseErrorPFI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pfi_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SwapResponsePFI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pfi_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*TxResponsePFI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pfi_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*BatchResponsePFI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pfi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pfi_proto_goTypes,
		DependencyIndexes: file_pfi_proto_depIdxs,
		MessageInfos:      file_pfi_proto_msgTypes,
	}.Build()
	File_pfi_proto = out.File
	file_pfi_proto_rawDesc = nil
	file_pfi_proto_goTypes = nil
	file_pfi_proto_depIdxs = nil
}
